name: .NET CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
            6.0.x
            8.0.x
    - name: Restore dependencies
      run: dotnet restore AverageCalculator/AverageCalculator.sln 
    
    - name: Build
      run: dotnet build AverageCalculator/AverageCalculator.sln --no-restore
    
    - name: Test
      run: dotnet test AverageCalculatorTest/AverageCalculatorTest.csproj --no-build --verbosity normal